## `Pandas`

In [ ]:
# Pandas:

Def:
    Pandas >> Python Data Analysis
    
Use Cases:
    1. Reading csv/excel/json file
    2. EDA
    3. Data Cleaning
    4. Encoding(OneHot, Label)
    5. Join Tables(left, right, inner, outer)
    6. Feature selection
    
Two Data Structure:
    
    # 1. Dataframes:
        Def:
            1. Two - dimensional data
            2. Tabular structure with rows and columns 
        Ex:
            df = pd.DataFrame('iris.csv')

    # 2. Series:
        Def:
            A Series is a one-dimensional array-like object 
            containing a sequence of values
        
        Ex:
            obj = pd.Series([4, 7, -5, 3])
            
    # 3. Panel:
    
        
 # read & write dataframes

    df = pd.read_csv('movies_data.csv', header = None)
    df = pd.read_excel('Emp_Records.xlsx', header = 0,index_col = 'Emp ID')
    df.to_csv('data.csv', index = False, header = False)
    crime_df.to_excel('movies1.xlsx', index = False, sheet_name = 'crime_movies')
    df.to_json('data1.json', orient = 'records')   
    
# How to create dataframe?

    1. list
    2. numpy array
    3. dict
    4. series
    5. csv file
    6. excel
    7. json

    import pandas as pd
    import numpy as np

    dict1 = {'columnA' : [2,3,4,5,6],
            'columnB' : [20,10,30,40,50]}

    df = pd.DataFrame(dict1)              # using dict
    df['columnC'] = [100,200,300,400,500] # using list
    df['columnD'] = np.array([9,8,7,6,5]) # using numpy array
    df['columnE'] = pd.Series([4,5,6,7,8])# using series
    df = pd.DataFrame(array1, columns = list('xyzw'), index = list('abcde')) # using array

# functions:

    3. df.shape   # return rows and columns
    4. df.columns # returns list of cols
    5. df.index   # returns list of rows
    6. df.axes    # returns names of rows & cols
    7. df.dtypes  # This returns a Series with the data type of each column.
    8. df.info    # returns index datatype & col & non null value, memory usage
    9. df.describe# generate descriptive statistics, only applicable on numeric data column
    10. df.head(n=) # returns first n rows, default value n=5
    12. df.tail()   # returns last n rows, default value n=5
    
    13. Access Columns
        1. df[col_name]       # returns one column
        2. df[[col_names_list]] # returns multiple column

    14. df.iloc[row_index, column_index]  # Selects single column or subset of columns by integer position
    15. df.loc[row_labels, column_labels] # Select both rows and columns by label

# detect missing values:

    1. df.isna() # returns boolean value for each ele in df
    2. df.isnull() # returns boolean same size object indicating if the values are NAN(np.nan)

# fill missing values:

x = '''
    1. mean()   # No outliers
    2. median() # median outliers
    3. mode()   # categorial variable Ex. Gender=M\F
    4. min()    # minimum value
    5. max()    # maximum value
    '''

1. df.fillna(x,inplace=True) # Replace all null values with x
   emp_df['Salary'].fillna(emp_df['Salary'].mean(), inplace = True)

2. df.dropna(axis=0,thresh=7,inplace=True) # thresh = 7 non null values
                                           # axis   = 0 (row), axis=1  (col)
    
3. df.drop([col_names],axis=1,index=,column=,inplace=True)
4. df.sort_index(axis=0,ascending=True,inplace=True,kind='quicksort') # sort rows by index values
2. df.sort_values(col,ascending=True,inplace=True) # Sort values by column in ascending
3. df.reset_index(drop=True,inplace=True) # drop the index and save the changes
4. df.set_index(col,inplace=True)    # set any col as index 
        
# pandas functions:

1. df[col_name].value_counts() # returns values with counts in columns 
2. df[col_name].value_counts().to_dict() # convert col name as key & ele as values.
3. df[col_name].unique() # returns unique values from column
4. df[col_name].nunique() #  returns n unique values from column
5. df[col_name].replace({'Male':1,'Female':2},inplace=True) #  replace values given in with other values
6. df[col_name].astype('float') # returns an object with change datatype for that column
7. df.insert(insertion_index,col,value)       
   df.insert(3,'Year',200,allow_duplicates=True) # insert in col year at index 3 value 200     
8. df.rename({'old_col_name':'new_col_name'},axis=1,inplace=True) # alter axis label  
9. df.apply(function,axis=0) # function applies on along with axis
   df.apply(np.nan)
10. df.groupby(col_name).get_group(group_name) # groups data frame using a series of columns


# pandas join

    1. append
        df1.append(df2)
        df1.append([df2,df3....dfn])

    2. concat
        pd.concat([df1, df2, ..... dfn], axis = 0, join = 'outer')

    3. merge : (Used to join only two dataframes )
        pd.merge(left_df, right_df, how = 'inner')

    4. join:
        df1.join(df2, how = 'left')

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# x = np.linspace(1,100,num=14)
x = np.random.randn(50)
np.mean(x)

plt.plot(x)
plt.show()

n = [ np.random.randn(50) for i in range(1,101)] # random numbers between 1-6
print('Mean Value = ',np.mean(n))
sns.distplot(n)

n = [ np.random.rand(50) for i in range(1,101)] # random numbers between 1-6
print('Mean Value = ',np.mean(n))
sns.distplot(n)

In [1]:
import numpy as np
import pandas as pd

In [ ]:

df1.append( ignore_index:= False, sort = False)
pd.concat([df1,df2],axis=0, join='outer', ignore_index= False)
pd.merge(data1, data2, on=['key1', 'key2']) 
df1.join(df2, lsuffix='_caller', rsuffix='_df1')

In [6]:
# Append

df1 = pd.DataFrame({'A':[10,20,30], 
                   'B' : [100,400,900]}, 
                   index = list('xyz'))

df2 =  pd.DataFrame({'A':[40,50,60], 
                    'B' : [1000,4000,9000]}, 
                    index = list('xmn'))
display(df1,df2)
df1.append(df2)

    A    B
x  10  100
y  20  400
z  30  900

    A     B
x  40  1000
m  50  4000
n  60  9000

C:\Users\ROCKSTAR\AppData\Local\Temp\ipykernel_17648\190658063.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)

    A     B
x  10   100
y  20   400
z  30   900
x  40  1000
m  50  4000
n  60  9000

In [20]:
# Concat

df1 = pd.DataFrame({'A':[10,20,30], 
                   'B' : [100,400,900]}, 
                   index = list('xyz'))

df2 =  pd.DataFrame({'C':[40,50,60], 
                    'D' : [1000,4000,9000]}, 
                    index = list('xmn'))

display(df1,df2)
display(pd.concat([df1,df2]))
pd.concat([df1,df2],1).reset_index(drop=True)

    A    B
x  10  100
y  20  400
z  30  900

    C     D
x  40  1000
m  50  4000
n  60  9000

      A      B     C       D
x  10.0  100.0   NaN     NaN
y  20.0  400.0   NaN     NaN
z  30.0  900.0   NaN     NaN
x   NaN    NaN  40.0  1000.0
m   NaN    NaN  50.0  4000.0
n   NaN    NaN  60.0  9000.0

C:\Users\ROCKSTAR\AppData\Local\Temp\ipykernel_17648\792954286.py:13: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only.
  pd.concat([df1,df2],1).reset_index(drop=True)

      A      B     C       D
0  10.0  100.0  40.0  1000.0
1  20.0  400.0   NaN     NaN
2  30.0  900.0   NaN     NaN
3   NaN    NaN  50.0  4000.0
4   NaN    NaN  60.0  9000.0

In [8]:
pd.concat([df1,df2],ignore_index=True)

      A      B     C       D
0  10.0  100.0   NaN     NaN
1  20.0  400.0   NaN     NaN
2  30.0  900.0   NaN     NaN
3   NaN    NaN  40.0  1000.0
4   NaN    NaN  50.0  4000.0
5   NaN    NaN  60.0  9000.0

In [24]:
data1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2' : ['K0', 'K1', 'K0', 'K1'],
                     'P'    : ['P0', 'P1', 'P2', 'P3'],
                     'Q'    : ['Q0', 'Q1', 'Q2', 'Q3']}) 

data2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'R'   : ['R0', 'R1', 'R2', 'R3'],
                      'S'   : ['S0', 'S1', 'S2', 'S3']})

display(pd.merge(data1, data2))
display(pd.merge(data1, data2, on=['key1', 'key2']))

  key1 key2   P   Q   R   S
0   K0   K0  P0  Q0  R0  S0
1   K1   K0  P2  Q2  R1  S1
2   K1   K0  P2  Q2  R2  S2

  key1 key2   P   Q   R   S
0   K0   K0  P0  Q0  R0  S0
1   K1   K0  P2  Q2  R1  S1
2   K1   K0  P2  Q2  R2  S2

In [45]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz','abc'],
                    'value': [1, 2, 3,4]})

df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'xyz'],
                    'value': [1,2,7]})

display(df1,df2)
pd.merge(df1,df2,how='outer',left_on='lkey',right_on='rkey')

  lkey  value
0  foo      1
1  bar      2
2  baz      3
3  abc      4

  rkey  value
0  foo      1
1  bar      2
2  xyz      7

  lkey  value_x rkey  value_y
0  foo      1.0  foo      1.0
1  bar      2.0  bar      2.0
2  baz      3.0  NaN      NaN
3  abc      4.0  NaN      NaN
4  NaN      NaN  xyz      7.0

In [62]:
df1['lkey']
df1.lkey
df1['lkey'].apply(lambda x : x.upper() + 'LKEY')

0    FOOLKEY
1    BARLKEY
2    BAZLKEY
3    ABCLKEY
Name: lkey, dtype: object

In [11]:
df1 = pd.DataFrame({'Student_ID': ['S1', 'S2', 'S3', 'S4', 'S5', 'S6'],
                'Student_Name': ['George', 'Michael', 'Dennis', 'David', 'Steve', 'Gary']})

df2 = pd.DataFrame({'Student_ID': ['S1', 'S2', 'S3'],
                  'Student_Name': ['Brett', 'Adam', 'Matthew']})

df1.join(df2, lsuffix='_caller', rsuffix='_df1')

  Student_ID_caller Student_Name_caller Student_ID_df1 Student_Name_df1
0                S1              George             S1            Brett
1                S2             Michael             S2             Adam
2                S3              Dennis             S3          Matthew
3                S4               David            NaN              NaN
4                S5               Steve            NaN              NaN
5                S6                Gary            NaN              NaN

In [22]:
l = [1,2,3,4,5]
df = pd.DataFrame(l,index=list('ABCDE'),columns=['Col1'])
df.T

      A  B  C  D  E
Col1  1  2  3  4  5

In [21]:
pd.Series(l)

0    1
1    2
2    3
3    4
4    5
dtype: int64