In [39]:
import pandas as pd
import numpy as np
import se

In [86]:
df = pd.read_excel("Datasheets_Case Study_Research Analyst_ETG_Pulses.xlsx",sheet_name = 'Weather Data', skiprows=1)

In [88]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,District 1,District 1.1,District 1.2,District 2,District 2.1,District 2.2,...,District 29.2,District 30,District 30.1,District 30.2,District 31,District 31.1,District 31.2,District 32,District 32.1,District 32.2
0,Date,YEAR,Day of the Year,Weekno.,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,...,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall
1,2013-01-01 00:00:00,2013,1,1,19.93,3.15,0,16.9,5.26,0,...,0,27.02,9.94,0,25.55,5.84,0,26.96,9.47,0
2,2013-02-01 00:00:00,2013,2,1,19.87,3.3,0,17.3,4.28,0,...,0,23.6,8.71,0,22.35,4.76,0,23.36,7.83,0
3,2013-03-01 00:00:00,2013,3,1,19.6,3.45,0,17.51,4.23,0,...,0,23.41,4.31,0,22.57,2.13,0,22.84,3.81,0
4,2013-04-01 00:00:00,2013,4,1,20.38,3.72,0,17.93,6.14,0,...,0,24.73,4.75,0,23.7,3.33,0,23.77,3.54,0

In [89]:
new_header = df.iloc[0]

In [90]:
df = df[1:]

In [91]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,District 1,District 1.1,District 1.2,District 2,District 2.1,District 2.2,...,District 29.2,District 30,District 30.1,District 30.2,District 31,District 31.1,District 31.2,District 32,District 32.1,District 32.2
1,2013-01-01 00:00:00,2013,1,1,19.93,3.15,0,16.9,5.26,0,...,0,27.02,9.94,0,25.55,5.84,0,26.96,9.47,0
2,2013-02-01 00:00:00,2013,2,1,19.87,3.3,0,17.3,4.28,0,...,0,23.6,8.71,0,22.35,4.76,0,23.36,7.83,0
3,2013-03-01 00:00:00,2013,3,1,19.6,3.45,0,17.51,4.23,0,...,0,23.41,4.31,0,22.57,2.13,0,22.84,3.81,0
4,2013-04-01 00:00:00,2013,4,1,20.38,3.72,0,17.93,6.14,0,...,0,24.73,4.75,0,23.7,3.33,0,23.77,3.54,0
5,2013-05-01 00:00:00,2013,5,1,18.98,2.93,0,16.81,3.19,0,...,0,24.04,5.03,0,22.12,2.79,0,23.87,4.08,0

In [92]:
df.columns = new_header

In [93]:
df.head()

,Date,YEAR,Day of the Year,Weekno.,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,...,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall
1,2013-01-01 00:00:00,2013,1,1,19.93,3.15,0,16.9,5.26,0,...,0,27.02,9.94,0,25.55,5.84,0,26.96,9.47,0
2,2013-02-01 00:00:00,2013,2,1,19.87,3.3,0,17.3,4.28,0,...,0,23.6,8.71,0,22.35,4.76,0,23.36,7.83,0
3,2013-03-01 00:00:00,2013,3,1,19.6,3.45,0,17.51,4.23,0,...,0,23.41,4.31,0,22.57,2.13,0,22.84,3.81,0
4,2013-04-01 00:00:00,2013,4,1,20.38,3.72,0,17.93,6.14,0,...,0,24.73,4.75,0,23.7,3.33,0,23.77,3.54,0
5,2013-05-01 00:00:00,2013,5,1,18.98,2.93,0,16.81,3.19,0,...,0,24.04,5.03,0,22.12,2.79,0,23.87,4.08,0

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4014 entries, 1 to 4014
Data columns (total 100 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             4014 non-null   object
 1   YEAR             4014 non-null   object
 2   Day of the Year  4014 non-null   object
 3   Weekno.          4014 non-null   object
 4   T2M_MAX          4014 non-null   object
 5   T2M_MIN          4014 non-null   object
 6   Rainfall         4014 non-null   object
 7   T2M_MAX          4014 non-null   object
 8   T2M_MIN          4014 non-null   object
 9   Rainfall         4014 non-null   object
 10  T2M_MAX          4014 non-null   object
 11  T2M_MIN          4014 non-null   object
 12  Rainfall         4014 non-null   object
 13  T2M_MAX          4014 non-null   object
 14  T2M_MIN          4014 non-null   object
 15  Rainfall         4014 non-null   object
 16  T2M_MAX          4014 non-null   object
 17  T2M_MIN          4014 non-null   object
 18  Rainfall         4014 non-null   object
 19  T2M_MAX          4014 non-null   object
 20  T2M_MIN          4014 non-null   object
 21  Rainfall         4014 non-null   object
 22  T2M_MAX          4014 non-null   object
 23  T2M_MIN          4014 non-null   object
 24  Rainfall         4014 non-null   object
 25  T2M_MAX          4014 non-null   object
 26  T2M_MIN          4014 non-null   object
 27  Rainfall         4014 non-null   object
 28  T2M_MAX          4014 non-null   object
 29  T2M_MIN          4014 non-null   object
 30  Rainfall         4014 non-null   object
 31  T2M_MAX          4014 non-null   object
 32  T2M_MIN          4014 non-null   object
 33  Rainfall         4014 non-null   object
 34  T2M_MAX          4014 non-null   object
 35  T2M_MIN          4014 non-null   object
 36  Rainfall         4014 non-null   object
 37  T2M_MAX          4014 non-null   object
 38  T2M_MIN          4014 non-null   object
 39  Rainfall         4014 non-null   object
 40  T2M_MAX          4014 non-null   object
 41  T2M_MIN          4014 non-null   object
 42  Rainfall         4014 non-null   object
 43  T2M_MAX          4014 non-null   object
 44  T2M_MIN          4014 non-null   object
 45  Rainfall         4014 non-null   object
 46  T2M_MAX          4014 non-null   object
 47  T2M_MIN          4014 non-null   object
 48  Rainfall         4014 non-null   object
 49  T2M_MAX          4014 non-null   object
 50  T2M_MIN          4014 non-null   object
 51  Rainfall         4014 non-null   object
 52  T2M_MAX          4014 non-null   object
 53  T2M_MIN          4014 non-null   object
 54  Rainfall         4014 non-null   object
 55  T2M_MAX          4014 non-null   object
 56  T2M_MIN          4014 non-null   object
 57  Rainfall         4014 non-null   object
 58  T2M_MAX          4014 non-null   object
 59  T2M_MIN          4014 non-null   object
 60  Rainfall         4014 non-null   object
 61  T2M_MAX          4014 non-null   object
 62  T2M_MIN          4014 non-null   object
 63  Rainfall         4014 non-null   object
 64  T2M_MAX          4014 non-null   object
 65  T2M_MIN          4014 non-null   object
 66  Rainfall         4014 non-null   object
 67  T2M_MAX          4014 non-null   object
 68  T2M_MIN          4014 non-null   object
 69  Rainfall         4014 non-null   object
 70  T2M_MAX          4014 non-null   object
 71  T2M_MIN          4014 non-null   object
 72  Rainfall         4014 non-null   object
 73  T2M_MAX          4014 non-null   object
 74  T2M_MIN          4014 non-null   object
 75  Rainfall         4014 non-null   object
 76  T2M_MAX          4014 non-null   object
 77  T2M_MIN          4014 non-null   object
 78  Rainfall         4014 non-null   object
 79  T2M_MAX          4014 non-null   object
 80  T2M_MIN          4014 non-null   object
 81  Rainfall         4014 non-null   object
 82  T2M_MAX          4014 non-null   object
 83  T2M_MIN          4014 non-null   object
 84  Rainfall         4014 non-null   object
 85  T2M_MAX          4014 non-null   object
 86  T2M_MIN          4014 non-null   object
 87  Rainfall         4014 non-null   object
 88  T2M_MAX          4014 non-null   object
 89  T2M_MIN          4014 non-null   object
 90  Rainfall         4014 non-null   object
 91  T2M_MAX          4014 non-null   object
 92  T2M_MIN          4014 non-null   object
 93  Rainfall         4014 non-null   object
 94  T2M_MAX          4014 non-null   object
 95  T2M_MIN          4014 non-null   object
 96  Rainfall         4014 non-null   object
 97  T2M_MAX          4014 non-null   object
 98  T2M_MIN          4014 non-null   object
 99  Rainfall         4014 non-null   object
dtypes: object(100)
memory usage: 3.1+ MB

In [97]:
df.iloc[:, 0] = pd.to_datetime(df.iloc[:, 0])

In [98]:
df.iloc[:, 1:] = df.iloc[:, 1:].astype(float)

In [102]:
df.dtypes

0
Date               object
YEAR               object
Day of the Year    object
Weekno.            object
T2M_MAX            object
                    ...
T2M_MIN            object
Rainfall           object
T2M_MAX            object
T2M_MIN            object
Rainfall           object
Length: 100, dtype: object

In [104]:
df['Date'] = pd.to_datetime(df['Date'])

In [106]:
df['YEAR'] = pd.to_datetime(df['YEAR'])

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4014 entries, 1 to 4014
Data columns (total 100 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             4014 non-null   datetime64[ns]
 1   YEAR             4014 non-null   datetime64[ns]
 2   Day of the Year  4014 non-null   object
 3   Weekno.          4014 non-null   object
 4   T2M_MAX          4014 non-null   object
 5   T2M_MIN          4014 non-null   object
 6   Rainfall         4014 non-null   object
 7   T2M_MAX          4014 non-null   object
 8   T2M_MIN          4014 non-null   object
 9   Rainfall         4014 non-null   object
 10  T2M_MAX          4014 non-null   object
 11  T2M_MIN          4014 non-null   object
 12  Rainfall         4014 non-null   object
 13  T2M_MAX          4014 non-null   object
 14  T2M_MIN          4014 non-null   object
 15  Rainfall         4014 non-null   object
 16  T2M_MAX          4014 non-null   object
 17  T2M_MIN          4014 non-null   object
 18  Rainfall         4014 non-null   object
 19  T2M_MAX          4014 non-null   object
 20  T2M_MIN          4014 non-null   object
 21  Rainfall         4014 non-null   object
 22  T2M_MAX          4014 non-null   object
 23  T2M_MIN          4014 non-null   object
 24  Rainfall         4014 non-null   object
 25  T2M_MAX          4014 non-null   object
 26  T2M_MIN          4014 non-null   object
 27  Rainfall         4014 non-null   object
 28  T2M_MAX          4014 non-null   object
 29  T2M_MIN          4014 non-null   object
 30  Rainfall         4014 non-null   object
 31  T2M_MAX          4014 non-null   object
 32  T2M_MIN          4014 non-null   object
 33  Rainfall         4014 non-null   object
 34  T2M_MAX          4014 non-null   object
 35  T2M_MIN          4014 non-null   object
 36  Rainfall         4014 non-null   object
 37  T2M_MAX          4014 non-null   object
 38  T2M_MIN          4014 non-null   object
 39  Rainfall         4014 non-null   object
 40  T2M_MAX          4014 non-null   object
 41  T2M_MIN          4014 non-null   object
 42  Rainfall         4014 non-null   object
 43  T2M_MAX          4014 non-null   object
 44  T2M_MIN          4014 non-null   object
 45  Rainfall         4014 non-null   object
 46  T2M_MAX          4014 non-null   object
 47  T2M_MIN          4014 non-null   object
 48  Rainfall         4014 non-null   object
 49  T2M_MAX          4014 non-null   object
 50  T2M_MIN          4014 non-null   object
 51  Rainfall         4014 non-null   object
 52  T2M_MAX          4014 non-null   object
 53  T2M_MIN          4014 non-null   object
 54  Rainfall         4014 non-null   object
 55  T2M_MAX          4014 non-null   object
 56  T2M_MIN          4014 non-null   object
 57  Rainfall         4014 non-null   object
 58  T2M_MAX          4014 non-null   object
 59  T2M_MIN          4014 non-null   object
 60  Rainfall         4014 non-null   object
 61  T2M_MAX          4014 non-null   object
 62  T2M_MIN          4014 non-null   object
 63  Rainfall         4014 non-null   object
 64  T2M_MAX          4014 non-null   object
 65  T2M_MIN          4014 non-null   object
 66  Rainfall         4014 non-null   object
 67  T2M_MAX          4014 non-null   object
 68  T2M_MIN          4014 non-null   object
 69  Rainfall         4014 non-null   object
 70  T2M_MAX          4014 non-null   object
 71  T2M_MIN          4014 non-null   object
 72  Rainfall         4014 non-null   object
 73  T2M_MAX          4014 non-null   object
 74  T2M_MIN          4014 non-null   object
 75  Rainfall         4014 non-null   object
 76  T2M_MAX          4014 non-null   object
 77  T2M_MIN          4014 non-null   object
 78  Rainfall         4014 non-null   object
 79  T2M_MAX          4014 non-null   object
 80  T2M_MIN          4014 non-null   object
 81  Rainfall         4014 non-null   object
 82  T2M_MAX          4014 non-null   object
 83  T2M_MIN          4014 non-null   object
 84  Rainfall         4014 non-null   object
 85  T2M_MAX          4014 non-null   object
 86  T2M_MIN          4014 non-null   object
 87  Rainfall         4014 non-null   object
 88  T2M_MAX          4014 non-null   object
 89  T2M_MIN          4014 non-null   object
 90  Rainfall         4014 non-null   object
 91  T2M_MAX          4014 non-null   object
 92  T2M_MIN          4014 non-null   object
 93  Rainfall         4014 non-null   object
 94  T2M_MAX          4014 non-null   object
 95  T2M_MIN          4014 non-null   object
 96  Rainfall         4014 non-null   object
 97  T2M_MAX          4014 non-null   object
 98  T2M_MIN          4014 non-null   object
 99  Rainfall         4014 non-null   object
dtypes: datetime64[ns](2), object(98)
memory usage: 3.1+ MB

In [108]:
df.head()

,Date,YEAR,Day of the Year,Weekno.,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,...,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall
1,2013-01-01,1970-01-01 00:00:00.000002013,1.0,1.0,19.93,3.15,0.0,16.9,5.26,0.0,...,0.0,27.02,9.94,0.0,25.55,5.84,0.0,26.96,9.47,0.0
2,2013-02-01,1970-01-01 00:00:00.000002013,2.0,1.0,19.87,3.3,0.0,17.3,4.28,0.0,...,0.0,23.6,8.71,0.0,22.35,4.76,0.0,23.36,7.83,0.0
3,2013-03-01,1970-01-01 00:00:00.000002013,3.0,1.0,19.6,3.45,0.0,17.51,4.23,0.0,...,0.0,23.41,4.31,0.0,22.57,2.13,0.0,22.84,3.81,0.0
4,2013-04-01,1970-01-01 00:00:00.000002013,4.0,1.0,20.38,3.72,0.0,17.93,6.14,0.0,...,0.0,24.73,4.75,0.0,23.7,3.33,0.0,23.77,3.54,0.0
5,2013-05-01,1970-01-01 00:00:00.000002013,5.0,1.0,18.98,2.93,0.0,16.81,3.19,0.0,...,0.0,24.04,5.03,0.0,22.12,2.79,0.0,23.87,4.08,0.0

In [122]:
df['YEAR']=df['Date'].dt.year

In [123]:
df[['Date', 'YEAR']]

0          Date  YEAR
1    2013-01-01  2013
2    2013-02-01  2013
3    2013-03-01  2013
4    2013-04-01  2013
5    2013-05-01  2013
...         ...   ...
4010 2023-12-24  2023
4011 2023-12-25  2023
4012 2023-12-26  2023
4013 2023-12-27  2023
4014 2023-12-28  2023

[4014 rows x 2 columns]

In [124]:
d1 = df[['Date', 'YEAR']]

In [113]:
df.iloc[:,2:] = df.iloc[:,2:].astype(float)

In [ ]:
df.iloc[]

In [125]:
d2 = df.iloc[:,2:].astype(float)

In [117]:
dd.dtypes

0
Day of the Year    float64
Weekno.            float64
T2M_MAX            float64
T2M_MIN            float64
Rainfall           float64
                    ...
T2M_MIN            float64
Rainfall           float64
T2M_MAX            float64
T2M_MIN            float64
Rainfall           float64
Length: 98, dtype: object

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4014 entries, 1 to 4014
Data columns (total 100 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             4014 non-null   datetime64[ns]
 1   YEAR             4014 non-null   datetime64[ns]
 2   Day of the Year  4014 non-null   object
 3   Weekno.          4014 non-null   object
 4   T2M_MAX          4014 non-null   object
 5   T2M_MIN          4014 non-null   object
 6   Rainfall         4014 non-null   object
 7   T2M_MAX          4014 non-null   object
 8   T2M_MIN          4014 non-null   object
 9   Rainfall         4014 non-null   object
 10  T2M_MAX          4014 non-null   object
 11  T2M_MIN          4014 non-null   object
 12  Rainfall         4014 non-null   object
 13  T2M_MAX          4014 non-null   object
 14  T2M_MIN          4014 non-null   object
 15  Rainfall         4014 non-null   object
 16  T2M_MAX          4014 non-null   object
 17  T2M_MIN          4014 non-null   object
 18  Rainfall         4014 non-null   object
 19  T2M_MAX          4014 non-null   object
 20  T2M_MIN          4014 non-null   object
 21  Rainfall         4014 non-null   object
 22  T2M_MAX          4014 non-null   object
 23  T2M_MIN          4014 non-null   object
 24  Rainfall         4014 non-null   object
 25  T2M_MAX          4014 non-null   object
 26  T2M_MIN          4014 non-null   object
 27  Rainfall         4014 non-null   object
 28  T2M_MAX          4014 non-null   object
 29  T2M_MIN          4014 non-null   object
 30  Rainfall         4014 non-null   object
 31  T2M_MAX          4014 non-null   object
 32  T2M_MIN          4014 non-null   object
 33  Rainfall         4014 non-null   object
 34  T2M_MAX          4014 non-null   object
 35  T2M_MIN          4014 non-null   object
 36  Rainfall         4014 non-null   object
 37  T2M_MAX          4014 non-null   object
 38  T2M_MIN          4014 non-null   object
 39  Rainfall         4014 non-null   object
 40  T2M_MAX          4014 non-null   object
 41  T2M_MIN          4014 non-null   object
 42  Rainfall         4014 non-null   object
 43  T2M_MAX          4014 non-null   object
 44  T2M_MIN          4014 non-null   object
 45  Rainfall         4014 non-null   object
 46  T2M_MAX          4014 non-null   object
 47  T2M_MIN          4014 non-null   object
 48  Rainfall         4014 non-null   object
 49  T2M_MAX          4014 non-null   object
 50  T2M_MIN          4014 non-null   object
 51  Rainfall         4014 non-null   object
 52  T2M_MAX          4014 non-null   object
 53  T2M_MIN          4014 non-null   object
 54  Rainfall         4014 non-null   object
 55  T2M_MAX          4014 non-null   object
 56  T2M_MIN          4014 non-null   object
 57  Rainfall         4014 non-null   object
 58  T2M_MAX          4014 non-null   object
 59  T2M_MIN          4014 non-null   object
 60  Rainfall         4014 non-null   object
 61  T2M_MAX          4014 non-null   object
 62  T2M_MIN          4014 non-null   object
 63  Rainfall         4014 non-null   object
 64  T2M_MAX          4014 non-null   object
 65  T2M_MIN          4014 non-null   object
 66  Rainfall         4014 non-null   object
 67  T2M_MAX          4014 non-null   object
 68  T2M_MIN          4014 non-null   object
 69  Rainfall         4014 non-null   object
 70  T2M_MAX          4014 non-null   object
 71  T2M_MIN          4014 non-null   object
 72  Rainfall         4014 non-null   object
 73  T2M_MAX          4014 non-null   object
 74  T2M_MIN          4014 non-null   object
 75  Rainfall         4014 non-null   object
 76  T2M_MAX          4014 non-null   object
 77  T2M_MIN          4014 non-null   object
 78  Rainfall         4014 non-null   object
 79  T2M_MAX          4014 non-null   object
 80  T2M_MIN          4014 non-null   object
 81  Rainfall         4014 non-null   object
 82  T2M_MAX          4014 non-null   object
 83  T2M_MIN          4014 non-null   object
 84  Rainfall         4014 non-null   object
 85  T2M_MAX          4014 non-null   object
 86  T2M_MIN          4014 non-null   object
 87  Rainfall         4014 non-null   object
 88  T2M_MAX          4014 non-null   object
 89  T2M_MIN          4014 non-null   object
 90  Rainfall         4014 non-null   object
 91  T2M_MAX          4014 non-null   object
 92  T2M_MIN          4014 non-null   object
 93  Rainfall         4014 non-null   object
 94  T2M_MAX          4014 non-null   object
 95  T2M_MIN          4014 non-null   object
 96  Rainfall         4014 non-null   object
 97  T2M_MAX          4014 non-null   object
 98  T2M_MIN          4014 non-null   object
 99  Rainfall         4014 non-null   object
dtypes: datetime64[ns](2), object(98)
memory usage: 3.1+ MB

In [129]:
df = pd.concat([d1,d2], axis=1)

In [131]:
df.dtypes

0
Date               datetime64[ns]
YEAR                        int32
Day of the Year           float64
Weekno.                   float64
T2M_MAX                   float64
                        ...
T2M_MIN                   float64
Rainfall                  float64
T2M_MAX                   float64
T2M_MIN                   float64
Rainfall                  float64
Length: 100, dtype: object

In [133]:
df.describe()

,Date,YEAR,Day of the Year,Weekno.,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,...,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall
count,4014,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,...,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000,4014.000000
mean,2018-06-30 12:00:00,2017.996263,182.955904,26.968112,33.489696,19.681114,1.256846,32.981682,20.073767,1.328473,...,1.824203,32.816290,19.558194,2.661432,31.625456,18.308876,1.851420,32.001393,19.074061,2.818009
min,2013-01-01 00:00:00,2013.000000,1.000000,1.000000,15.110000,1.190000,0.000000,14.450000,1.160000,0.000000,...,0.000000,14.950000,2.260000,0.000000,16.350000,1.550000,0.000000,14.110000,1.290000,0.000000
25%,2015-10-01 06:00:00,2015.000000,92.000000,14.000000,29.032500,13.302500,0.000000,27.292500,13.072500,0.000000,...,0.000000,28.690000,13.900000,0.000000,28.150000,13.592500,0.000000,27.980000,13.210000,0.000000
50%,2018-06-30 12:00:00,2018.000000,183.000000,27.000000,34.310000,21.510000,0.000000,34.340000,21.810000,0.000000,...,0.000000,31.475000,21.105000,0.000000,30.900000,19.940000,0.000000,30.690000,20.765000,0.000000
75%,2021-03-29 18:00:00,2021.000000,274.000000,40.000000,38.080000,26.010000,0.220000,38.300000,26.867500,0.390000,...,0.690000,36.857500,24.830000,0.840000,35.300000,23.370000,0.300000,36.267500,24.340000,1.050000
max,2023-12-28 00:00:00,2023.000000,366.000000,53.000000,47.120000,32.830000,66.800000,46.940000,34.150000,45.080000,...,74.700000,48.190000,34.550000,135.010000,45.390000,29.480000,97.400000,47.350000,33.510000,123.040000
std,NaN,3.160423,105.355255,15.056666,6.195805,7.479453,4.070584,7.037065,7.849777,4.151136,...,5.367276,6.019685,6.733258,7.939058,5.294727,6.178969,6.162162,6.064792,6.805572,8.102009

In [139]:
for i in df.count():
    if i < 4014:
        
        print(i)

In [147]:
for i in df.isnull().sum():
    if i > 0:
        
        print(i)

In [148]:
df.head()

,Date,YEAR,Day of the Year,Weekno.,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,...,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall
1,2013-01-01,2013,1.0,1.0,19.93,3.15,0.0,16.90,5.26,0.0,...,0.0,27.02,9.94,0.0,25.55,5.84,0.0,26.96,9.47,0.0
2,2013-02-01,2013,2.0,1.0,19.87,3.30,0.0,17.30,4.28,0.0,...,0.0,23.60,8.71,0.0,22.35,4.76,0.0,23.36,7.83,0.0
3,2013-03-01,2013,3.0,1.0,19.60,3.45,0.0,17.51,4.23,0.0,...,0.0,23.41,4.31,0.0,22.57,2.13,0.0,22.84,3.81,0.0
4,2013-04-01,2013,4.0,1.0,20.38,3.72,0.0,17.93,6.14,0.0,...,0.0,24.73,4.75,0.0,23.70,3.33,0.0,23.77,3.54,0.0
5,2013-05-01,2013,5.0,1.0,18.98,2.93,0.0,16.81,3.19,0.0,...,0.0,24.04,5.03,0.0,22.12,2.79,0.0,23.87,4.08,0.0

In [149]:
df_monthly = df.groupby(pd.Grouper(key='Date', freq='M')).sum()

In [150]:
df_monthly

,YEAR,Day of the Year,Weekno.,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,...,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall
Date,,,,,,,,,,,,,,,,,,,,,
2013-01-31,62403,2428.0,370.0,814.87,368.36,27.05,794.96,361.39,36.91,834.25,...,22.41,890.04,389.79,23.79,838.09,349.21,32.84,869.90,375.98,24.01
2013-02-28,56364,2846.0,426.0,813.85,398.32,16.58,780.67,409.35,20.28,837.80,...,32.96,841.80,416.71,70.41,821.66,392.17,16.26,815.68,397.68,79.96
2013-03-31,62403,3573.0,533.0,1018.93,564.08,11.00,995.30,557.16,24.25,1037.67,...,52.74,1049.46,564.52,66.00,1001.46,526.84,7.26,1027.52,545.60,68.94
2013-04-30,60390,4053.0,601.0,1084.39,647.53,5.58,1068.35,648.32,12.93,1098.82,...,8.38,1098.84,649.15,34.97,1047.59,609.73,21.33,1072.04,632.45,39.50
2013-05-31,62403,4756.0,701.0,1208.52,748.42,13.29,1215.23,761.22,29.82,1213.83,...,45.78,1220.77,766.14,41.77,1145.46,688.41,36.98,1200.65,748.38,48.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-31,62713,6540.0,948.0,1090.83,760.66,32.19,1103.52,786.37,7.90,1061.47,...,94.69,1044.47,739.67,143.70,960.97,672.10,48.40,1078.86,775.80,130.70
2023-09-30,60690,6867.0,993.0,1044.10,746.70,59.51,1034.12,735.29,94.70,1040.03,...,52.16,980.11,704.40,40.10,936.17,668.74,153.30,1017.20,726.79,46.70
2023-10-31,62713,7723.0,1117.0,1034.87,700.99,36.60,1010.24,677.73,27.10,1059.94,...,28.20,1007.50,664.59,30.60,981.66,643.80,23.50,1019.74,669.06,52.50
2023-11-30,60690,7989.0,1154.0,893.39,556.91,7.70,865.18,532.89,1.13,911.83,...,30.60,870.72,549.83,25.80,856.11,507.32,26.40,881.01,554.42,51.00
2023-12-31,56644,7814.0,1129.0,819.71,474.80,2.94,792.86,459.25,6.18,825.47,...,0.39,777.62,458.61,6.00,777.58,440.27,2.91,776.33,443.27,3.30

In [ ]:
for i in df_monthly.columns:
    if i == ''

In [161]:
df_monthly['Monthly_Rainfall'] = df_monthly.loc[:, df_monthly.columns.str.startswith('Rainfall')].sum(axis=1)

In [162]:
df_monthly.head()

,YEAR,Day of the Year,Weekno.,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,...,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,Monthly_Rainfall
Date,,,,,,,,,,,,,,,,,,,,,
2013-01-31,62403,2428.0,370.0,814.87,368.36,27.05,794.96,361.39,36.91,834.25,...,890.04,389.79,23.79,838.09,349.21,32.84,869.90,375.98,24.01,860.53
2013-02-28,56364,2846.0,426.0,813.85,398.32,16.58,780.67,409.35,20.28,837.80,...,841.80,416.71,70.41,821.66,392.17,16.26,815.68,397.68,79.96,878.11
2013-03-31,62403,3573.0,533.0,1018.93,564.08,11.00,995.30,557.16,24.25,1037.67,...,1049.46,564.52,66.00,1001.46,526.84,7.26,1027.52,545.60,68.94,923.53
2013-04-30,60390,4053.0,601.0,1084.39,647.53,5.58,1068.35,648.32,12.93,1098.82,...,1098.84,649.15,34.97,1047.59,609.73,21.33,1072.04,632.45,39.50,647.59
2013-05-31,62403,4756.0,701.0,1208.52,748.42,13.29,1215.23,761.22,29.82,1213.83,...,1220.77,766.14,41.77,1145.46,688.41,36.98,1200.65,748.38,48.84,994.04

In [166]:
Monthly_Rainfall_MM = df_monthly.iloc[:,-1]

In [191]:
all_data = pd.DataFrame(Monthly_Rainfall_MM )

In [192]:
all_data.head()

            Monthly_Rainfall
Date
2013-01-31            860.53
2013-02-28            878.11
2013-03-31            923.53
2013-04-30            647.59
2013-05-31            994.04

In [169]:
df.head()

,Date,YEAR,Day of the Year,Weekno.,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,...,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall,T2M_MAX,T2M_MIN,Rainfall
1,2013-01-01,2013,1.0,1.0,19.93,3.15,0.0,16.90,5.26,0.0,...,0.0,27.02,9.94,0.0,25.55,5.84,0.0,26.96,9.47,0.0
2,2013-02-01,2013,2.0,1.0,19.87,3.30,0.0,17.30,4.28,0.0,...,0.0,23.60,8.71,0.0,22.35,4.76,0.0,23.36,7.83,0.0
3,2013-03-01,2013,3.0,1.0,19.60,3.45,0.0,17.51,4.23,0.0,...,0.0,23.41,4.31,0.0,22.57,2.13,0.0,22.84,3.81,0.0
4,2013-04-01,2013,4.0,1.0,20.38,3.72,0.0,17.93,6.14,0.0,...,0.0,24.73,4.75,0.0,23.70,3.33,0.0,23.77,3.54,0.0
5,2013-05-01,2013,5.0,1.0,18.98,2.93,0.0,16.81,3.19,0.0,...,0.0,24.04,5.03,0.0,22.12,2.79,0.0,23.87,4.08,0.0

In [170]:
df_monthly_max = df.groupby(pd.Grouper(key='Date', freq='M'))['T2M_MAX'].max().reset_index()

In [172]:
df_monthly_max

,Date,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,...,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX
0,2013-01-31,43.67,43.06,44.15,44.17,43.50,44.54,43.41,43.08,42.22,...,42.37,42.84,43.69,41.15,41.89,42.37,41.64,43.49,41.07,42.32
1,2013-02-28,43.08,42.57,43.76,44.07,44.08,43.79,42.76,42.15,41.58,...,41.73,42.33,42.76,40.73,41.26,41.23,40.69,41.94,39.89,41.15
2,2013-03-31,44.10,43.73,44.40,44.44,44.44,44.66,43.82,43.98,43.30,...,42.00,42.01,41.69,40.90,43.13,41.42,43.05,42.83,40.48,42.00
3,2013-04-30,44.71,44.77,44.96,44.83,44.54,45.15,43.99,44.37,42.88,...,42.76,42.46,43.12,40.73,43.29,40.96,44.32,43.76,40.71,42.93
4,2013-05-31,44.94,45.31,44.97,45.61,46.20,45.17,44.22,45.72,44.50,...,44.80,45.02,45.68,43.48,45.22,43.69,47.19,46.46,42.78,45.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,2023-08-31,43.00,42.00,41.00,49.00,41.90,41.00,40.00,42.00,40.00,...,41.00,41.00,42.00,40.00,41.00,41.00,41.00,41.00,39.00,41.00
128,2023-09-30,42.00,41.00,42.00,48.00,42.70,42.00,40.00,42.00,40.00,...,41.00,42.00,43.00,40.00,40.00,41.00,40.00,41.00,39.00,41.00
129,2023-10-31,43.00,42.00,43.00,47.00,43.00,43.00,41.00,42.00,40.00,...,42.00,43.00,43.00,41.00,41.00,41.00,40.00,41.00,40.00,40.00
130,2023-11-30,42.00,40.00,44.00,46.00,44.00,44.00,42.00,43.00,41.00,...,43.00,43.00,44.00,42.00,42.00,42.00,41.00,43.00,41.00,41.00
131,2023-12-31,44.00,44.00,45.00,47.00,45.00,45.00,44.00,44.00,44.00,...,44.00,44.00,45.00,43.00,44.00,43.00,45.00,44.00,42.00,44.00

In [185]:
dum = df_monthly_max.iloc[:,1:]

In [186]:
dum

,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,...,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX
0,43.67,43.06,44.15,44.17,43.50,44.54,43.41,43.08,42.22,43.98,...,42.37,42.84,43.69,41.15,41.89,42.37,41.64,43.49,41.07,42.32
1,43.08,42.57,43.76,44.07,44.08,43.79,42.76,42.15,41.58,44.16,...,41.73,42.33,42.76,40.73,41.26,41.23,40.69,41.94,39.89,41.15
2,44.10,43.73,44.40,44.44,44.44,44.66,43.82,43.98,43.30,44.93,...,42.00,42.01,41.69,40.90,43.13,41.42,43.05,42.83,40.48,42.00
3,44.71,44.77,44.96,44.83,44.54,45.15,43.99,44.37,42.88,45.55,...,42.76,42.46,43.12,40.73,43.29,40.96,44.32,43.76,40.71,42.93
4,44.94,45.31,44.97,45.61,46.20,45.17,44.22,45.72,44.50,47.12,...,44.80,45.02,45.68,43.48,45.22,43.69,47.19,46.46,42.78,45.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,43.00,42.00,41.00,49.00,41.90,41.00,40.00,42.00,40.00,43.00,...,41.00,41.00,42.00,40.00,41.00,41.00,41.00,41.00,39.00,41.00
128,42.00,41.00,42.00,48.00,42.70,42.00,40.00,42.00,40.00,42.00,...,41.00,42.00,43.00,40.00,40.00,41.00,40.00,41.00,39.00,41.00
129,43.00,42.00,43.00,47.00,43.00,43.00,41.00,42.00,40.00,41.00,...,42.00,43.00,43.00,41.00,41.00,41.00,40.00,41.00,40.00,40.00
130,42.00,40.00,44.00,46.00,44.00,44.00,42.00,43.00,41.00,43.00,...,43.00,43.00,44.00,42.00,42.00,42.00,41.00,43.00,41.00,41.00
131,44.00,44.00,45.00,47.00,45.00,45.00,44.00,44.00,44.00,45.00,...,44.00,44.00,45.00,43.00,44.00,43.00,45.00,44.00,42.00,44.00

In [187]:
dum['Max_Number'] = dum.max(axis=1)

In [188]:
dum.head()

,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,...,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,T2M_MAX,Max_Number
0,43.67,43.06,44.15,44.17,43.50,44.54,43.41,43.08,42.22,43.98,...,42.84,43.69,41.15,41.89,42.37,41.64,43.49,41.07,42.32,44.83
1,43.08,42.57,43.76,44.07,44.08,43.79,42.76,42.15,41.58,44.16,...,42.33,42.76,40.73,41.26,41.23,40.69,41.94,39.89,41.15,45.16
2,44.10,43.73,44.40,44.44,44.44,44.66,43.82,43.98,43.30,44.93,...,42.01,41.69,40.90,43.13,41.42,43.05,42.83,40.48,42.00,45.60
3,44.71,44.77,44.96,44.83,44.54,45.15,43.99,44.37,42.88,45.55,...,42.46,43.12,40.73,43.29,40.96,44.32,43.76,40.71,42.93,45.74
4,44.94,45.31,44.97,45.61,46.20,45.17,44.22,45.72,44.50,47.12,...,45.02,45.68,43.48,45.22,43.69,47.19,46.46,42.78,45.60,48.05

In [189]:
Maximum_Temperature = dum['Max_Number']

In [201]:
Maximum_Temperature = pd.DataFrame(Maximum_Temperature)

In [204]:
Maximum_Temperature

     Max_Number
0         44.83
1         45.16
2         45.60
3         45.74
4         48.05
..          ...
127       49.00
128       48.00
129       47.00
130       46.00
131       47.00

[132 rows x 1 columns]

In [202]:
all_data['Maximum_Temperature'] = Maximum_Temperature

In [203]:
all_data

            Monthly_Rainfall  Maximum_Temperature
Date
2013-01-31            860.53                  NaN
2013-02-28            878.11                  NaN
2013-03-31            923.53                  NaN
2013-04-30            647.59                  NaN
2013-05-31            994.04                  NaN
...                      ...                  ...
2023-08-31           1842.90                  NaN
2023-09-30           3575.49                  NaN
2023-10-31           1010.25                  NaN
2023-11-30            913.46                  NaN
2023-12-31            152.46                  NaN

[132 rows x 2 columns]

In [200]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 132 entries, 2013-01-31 to 2023-12-31
Freq: M
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Monthly_Rainfall     132 non-null    float64
 1   Maximum_Temperature  0 non-null      float64
dtypes: float64(2)
memory usage: 7.2 KB